/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Standard = IDL.Variant({
  'NIST_CSF' : IDL.Null,
  'CMMC' : IDL.Null,
  'SOC2' : IDL.Null,
  'NERC_CIP' : IDL.Null,
  'ISO27001' : IDL.Null,
  'IEC62443' : IDL.Null,
});
export const ControlFamily = IDL.Variant({
  'Physical_Security' : IDL.Null,
  'Security_Assessment' : IDL.Null,
  'Continuous_Monitoring' : IDL.Null,
  'Cryptography' : IDL.Null,
  'Asset_Management' : IDL.Null,
  'Communications_Security' : IDL.Null,
  'Access_Control' : IDL.Null,
  'Operations_Security' : IDL.Null,
});
export const ComplianceControl = IDL.Record({
  'id' : IDL.Text,
  'description' : IDL.Text,
  'standard' : Standard,
  'family' : ControlFamily,
});
export const CrosswalkMapping = IDL.Record({
  'sourceControlId' : IDL.Text,
  'sourceStandard' : Standard,
  'targetControlId' : IDL.Text,
  'targetStandard' : Standard,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EvidenceType = IDL.Variant({
  'Log' : IDL.Null,
  'Policy' : IDL.Null,
  'Document' : IDL.Null,
  'Screenshot' : IDL.Null,
});
export const EvidenceStatus = IDL.Variant({
  'Active' : IDL.Null,
  'Expired' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Time = IDL.Int;
export const TaskPriority = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const ControlStatus = IDL.Variant({
  'NotApplicable' : IDL.Null,
  'NonCompliant' : IDL.Null,
  'Partial' : IDL.Null,
  'Compliant' : IDL.Null,
});
export const Assessment = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'controlsStatus' : IDL.Vec(IDL.Tuple(IDL.Text, ControlStatus)),
  'lastUpdated' : Time,
  'standard' : Standard,
});
export const EvidenceRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : EvidenceStatus,
  'expiryDate' : IDL.Opt(Time),
  'name' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'controlId' : IDL.Text,
  'notes' : IDL.Text,
  'standard' : Standard,
  'linkedAssessmentId' : IDL.Opt(IDL.Text),
  'evidenceType' : EvidenceType,
});
export const TaskStatus = IDL.Variant({
  'OnHold' : IDL.Null,
  'Open' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
});
export const ImplementationTask = IDL.Record({
  'id' : IDL.Text,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'controlId' : IDL.Text,
  'priority' : TaskPriority,
  'standard' : Standard,
  'linkedAssessmentId' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'organization' : IDL.Text,
});
export const ComplianceReport = IDL.Record({
  'notApplicableCount' : IDL.Nat,
  'partialCount' : IDL.Nat,
  'compliantCount' : IDL.Nat,
  'totalControls' : IDL.Nat,
  'nonCompliantCount' : IDL.Nat,
  'standard' : Standard,
  'compliancePercentage' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComplianceControl' : IDL.Func([ComplianceControl], [], []),
  'addCrosswalkMapping' : IDL.Func([CrosswalkMapping], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAssessment' : IDL.Func([Standard], [IDL.Text], []),
  'createEvidenceRecord' : IDL.Func(
      [
        IDL.Text,
        Standard,
        IDL.Text,
        EvidenceType,
        EvidenceStatus,
        IDL.Opt(Time),
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Text],
      [],
    ),
  'createImplementationTask' : IDL.Func(
      [IDL.Text, Standard, IDL.Text, IDL.Text, TaskPriority, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'deleteAssessment' : IDL.Func([IDL.Text], [], []),
  'deleteComplianceControl' : IDL.Func([IDL.Text], [], []),
  'deleteCrosswalkMapping' : IDL.Func(
      [Standard, IDL.Text, Standard, IDL.Text],
      [],
      [],
    ),
  'deleteEvidenceRecord' : IDL.Func([IDL.Text], [], []),
  'deleteImplementationTask' : IDL.Func([IDL.Text], [], []),
  'getAllAssessments' : IDL.Func([], [IDL.Vec(Assessment)], ['query']),
  'getAllComplianceControls' : IDL.Func(
      [],
      [IDL.Vec(ComplianceControl)],
      ['query'],
    ),
  'getAllCrosswalkMappings' : IDL.Func(
      [],
      [IDL.Vec(CrosswalkMapping)],
      ['query'],
    ),
  'getAllEvidenceRecords' : IDL.Func([], [IDL.Vec(EvidenceRecord)], ['query']),
  'getAllImplementationTasks' : IDL.Func(
      [],
      [IDL.Vec(ImplementationTask)],
      ['query'],
    ),
  'getAssessment' : IDL.Func([IDL.Text], [Assessment], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComplianceControl' : IDL.Func([IDL.Text], [ComplianceControl], ['query']),
  'getComplianceReport' : IDL.Func([Standard], [ComplianceReport], ['query']),
  'getControlsByStandard' : IDL.Func(
      [Standard],
      [IDL.Vec(ComplianceControl)],
      ['query'],
    ),
  'getCrosswalkMappings' : IDL.Func(
      [Standard, Standard],
      [IDL.Vec(CrosswalkMapping)],
      ['query'],
    ),
  'getEvidenceByControl' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(EvidenceRecord)],
      ['query'],
    ),
  'getEvidenceByStandard' : IDL.Func(
      [Standard],
      [IDL.Vec(EvidenceRecord)],
      ['query'],
    ),
  'getEvidenceCoverageSummary' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Standard, IDL.Nat))],
      ['query'],
    ),
  'getEvidenceRecord' : IDL.Func([IDL.Text], [EvidenceRecord], ['query']),
  'getImplementationTask' : IDL.Func(
      [IDL.Text],
      [ImplementationTask],
      ['query'],
    ),
  'getRecentAssessmentActivity' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Assessment)],
      ['query'],
    ),
  'getTasksByPriority' : IDL.Func(
      [TaskPriority],
      [IDL.Vec(ImplementationTask)],
      ['query'],
    ),
  'getTasksByPrioritySorted' : IDL.Func(
      [],
      [IDL.Vec(ImplementationTask)],
      ['query'],
    ),
  'getTasksByStandard' : IDL.Func(
      [Standard],
      [IDL.Vec(ImplementationTask)],
      ['query'],
    ),
  'getUserAssessments' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Assessment)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAssessmentControlStatus' : IDL.Func(
      [IDL.Text, IDL.Text, ControlStatus],
      [],
      [],
    ),
  'updateComplianceControl' : IDL.Func([ComplianceControl], [], []),
  'updateEvidenceRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        EvidenceType,
        EvidenceStatus,
        IDL.Opt(Time),
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateImplementationTask' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, TaskPriority, TaskStatus],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Standard = IDL.Variant({
    'NIST_CSF' : IDL.Null,
    'CMMC' : IDL.Null,
    'SOC2' : IDL.Null,
    'NERC_CIP' : IDL.Null,
    'ISO27001' : IDL.Null,
    'IEC62443' : IDL.Null,
  });
  const ControlFamily = IDL.Variant({
    'Physical_Security' : IDL.Null,
    'Security_Assessment' : IDL.Null,
    'Continuous_Monitoring' : IDL.Null,
    'Cryptography' : IDL.Null,
    'Asset_Management' : IDL.Null,
    'Communications_Security' : IDL.Null,
    'Access_Control' : IDL.Null,
    'Operations_Security' : IDL.Null,
  });
  const ComplianceControl = IDL.Record({
    'id' : IDL.Text,
    'description' : IDL.Text,
    'standard' : Standard,
    'family' : ControlFamily,
  });
  const CrosswalkMapping = IDL.Record({
    'sourceControlId' : IDL.Text,
    'sourceStandard' : Standard,
    'targetControlId' : IDL.Text,
    'targetStandard' : Standard,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EvidenceType = IDL.Variant({
    'Log' : IDL.Null,
    'Policy' : IDL.Null,
    'Document' : IDL.Null,
    'Screenshot' : IDL.Null,
  });
  const EvidenceStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Expired' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Time = IDL.Int;
  const TaskPriority = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const ControlStatus = IDL.Variant({
    'NotApplicable' : IDL.Null,
    'NonCompliant' : IDL.Null,
    'Partial' : IDL.Null,
    'Compliant' : IDL.Null,
  });
  const Assessment = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'controlsStatus' : IDL.Vec(IDL.Tuple(IDL.Text, ControlStatus)),
    'lastUpdated' : Time,
    'standard' : Standard,
  });
  const EvidenceRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : EvidenceStatus,
    'expiryDate' : IDL.Opt(Time),
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'controlId' : IDL.Text,
    'notes' : IDL.Text,
    'standard' : Standard,
    'linkedAssessmentId' : IDL.Opt(IDL.Text),
    'evidenceType' : EvidenceType,
  });
  const TaskStatus = IDL.Variant({
    'OnHold' : IDL.Null,
    'Open' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const ImplementationTask = IDL.Record({
    'id' : IDL.Text,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'controlId' : IDL.Text,
    'priority' : TaskPriority,
    'standard' : Standard,
    'linkedAssessmentId' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'organization' : IDL.Text,
  });
  const ComplianceReport = IDL.Record({
    'notApplicableCount' : IDL.Nat,
    'partialCount' : IDL.Nat,
    'compliantCount' : IDL.Nat,
    'totalControls' : IDL.Nat,
    'nonCompliantCount' : IDL.Nat,
    'standard' : Standard,
    'compliancePercentage' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComplianceControl' : IDL.Func([ComplianceControl], [], []),
    'addCrosswalkMapping' : IDL.Func([CrosswalkMapping], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAssessment' : IDL.Func([Standard], [IDL.Text], []),
    'createEvidenceRecord' : IDL.Func(
        [
          IDL.Text,
          Standard,
          IDL.Text,
          EvidenceType,
          EvidenceStatus,
          IDL.Opt(Time),
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Text],
        [],
      ),
    'createImplementationTask' : IDL.Func(
        [
          IDL.Text,
          Standard,
          IDL.Text,
          IDL.Text,
          TaskPriority,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Text],
        [],
      ),
    'deleteAssessment' : IDL.Func([IDL.Text], [], []),
    'deleteComplianceControl' : IDL.Func([IDL.Text], [], []),
    'deleteCrosswalkMapping' : IDL.Func(
        [Standard, IDL.Text, Standard, IDL.Text],
        [],
        [],
      ),
    'deleteEvidenceRecord' : IDL.Func([IDL.Text], [], []),
    'deleteImplementationTask' : IDL.Func([IDL.Text], [], []),
    'getAllAssessments' : IDL.Func([], [IDL.Vec(Assessment)], ['query']),
    'getAllComplianceControls' : IDL.Func(
        [],
        [IDL.Vec(ComplianceControl)],
        ['query'],
      ),
    'getAllCrosswalkMappings' : IDL.Func(
        [],
        [IDL.Vec(CrosswalkMapping)],
        ['query'],
      ),
    'getAllEvidenceRecords' : IDL.Func(
        [],
        [IDL.Vec(EvidenceRecord)],
        ['query'],
      ),
    'getAllImplementationTasks' : IDL.Func(
        [],
        [IDL.Vec(ImplementationTask)],
        ['query'],
      ),
    'getAssessment' : IDL.Func([IDL.Text], [Assessment], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComplianceControl' : IDL.Func(
        [IDL.Text],
        [ComplianceControl],
        ['query'],
      ),
    'getComplianceReport' : IDL.Func([Standard], [ComplianceReport], ['query']),
    'getControlsByStandard' : IDL.Func(
        [Standard],
        [IDL.Vec(ComplianceControl)],
        ['query'],
      ),
    'getCrosswalkMappings' : IDL.Func(
        [Standard, Standard],
        [IDL.Vec(CrosswalkMapping)],
        ['query'],
      ),
    'getEvidenceByControl' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(EvidenceRecord)],
        ['query'],
      ),
    'getEvidenceByStandard' : IDL.Func(
        [Standard],
        [IDL.Vec(EvidenceRecord)],
        ['query'],
      ),
    'getEvidenceCoverageSummary' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Standard, IDL.Nat))],
        ['query'],
      ),
    'getEvidenceRecord' : IDL.Func([IDL.Text], [EvidenceRecord], ['query']),
    'getImplementationTask' : IDL.Func(
        [IDL.Text],
        [ImplementationTask],
        ['query'],
      ),
    'getRecentAssessmentActivity' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Assessment)],
        ['query'],
      ),
    'getTasksByPriority' : IDL.Func(
        [TaskPriority],
        [IDL.Vec(ImplementationTask)],
        ['query'],
      ),
    'getTasksByPrioritySorted' : IDL.Func(
        [],
        [IDL.Vec(ImplementationTask)],
        ['query'],
      ),
    'getTasksByStandard' : IDL.Func(
        [Standard],
        [IDL.Vec(ImplementationTask)],
        ['query'],
      ),
    'getUserAssessments' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Assessment)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAssessmentControlStatus' : IDL.Func(
        [IDL.Text, IDL.Text, ControlStatus],
        [],
        [],
      ),
    'updateComplianceControl' : IDL.Func([ComplianceControl], [], []),
    'updateEvidenceRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          EvidenceType,
          EvidenceStatus,
          IDL.Opt(Time),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateImplementationTask' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, TaskPriority, TaskStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };