/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assessment {
  'id' : string,
  'createdAt' : Time,
  'user' : Principal,
  'controlsStatus' : Array<[string, ControlStatus]>,
  'lastUpdated' : Time,
  'standard' : Standard,
}
export interface ComplianceControl {
  'id' : string,
  'description' : string,
  'standard' : Standard,
  'family' : ControlFamily,
}
export interface ComplianceReport {
  'notApplicableCount' : bigint,
  'partialCount' : bigint,
  'compliantCount' : bigint,
  'totalControls' : bigint,
  'nonCompliantCount' : bigint,
  'standard' : Standard,
  'compliancePercentage' : number,
}
export type ControlFamily = { 'Physical_Security' : null } |
  { 'Security_Assessment' : null } |
  { 'Continuous_Monitoring' : null } |
  { 'Cryptography' : null } |
  { 'Asset_Management' : null } |
  { 'Communications_Security' : null } |
  { 'Access_Control' : null } |
  { 'Operations_Security' : null };
export type ControlStatus = { 'NotApplicable' : null } |
  { 'NonCompliant' : null } |
  { 'Partial' : null } |
  { 'Compliant' : null };
export interface CrosswalkMapping {
  'sourceControlId' : string,
  'sourceStandard' : Standard,
  'targetControlId' : string,
  'targetStandard' : Standard,
}
export interface EvidenceRecord {
  'id' : string,
  'status' : EvidenceStatus,
  'expiryDate' : [] | [Time],
  'name' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'controlId' : string,
  'notes' : string,
  'standard' : Standard,
  'linkedAssessmentId' : [] | [string],
  'evidenceType' : EvidenceType,
}
export type EvidenceStatus = { 'Active' : null } |
  { 'Expired' : null } |
  { 'Pending' : null };
export type EvidenceType = { 'Log' : null } |
  { 'Policy' : null } |
  { 'Document' : null } |
  { 'Screenshot' : null };
export interface ImplementationTask {
  'id' : string,
  'status' : TaskStatus,
  'title' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'description' : string,
  'controlId' : string,
  'priority' : TaskPriority,
  'standard' : Standard,
  'linkedAssessmentId' : [] | [string],
}
export type Standard = { 'NIST_CSF' : null } |
  { 'CMMC' : null } |
  { 'SOC2' : null } |
  { 'NERC_CIP' : null } |
  { 'ISO27001' : null } |
  { 'IEC62443' : null };
export type TaskPriority = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export type TaskStatus = { 'OnHold' : null } |
  { 'Open' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'organization' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComplianceControl' : ActorMethod<[ComplianceControl], undefined>,
  'addCrosswalkMapping' : ActorMethod<[CrosswalkMapping], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAssessment' : ActorMethod<[Standard], string>,
  'createEvidenceRecord' : ActorMethod<
    [
      string,
      Standard,
      string,
      EvidenceType,
      EvidenceStatus,
      [] | [Time],
      string,
      [] | [string],
    ],
    string
  >,
  'createImplementationTask' : ActorMethod<
    [string, Standard, string, string, TaskPriority, [] | [string]],
    string
  >,
  'deleteAssessment' : ActorMethod<[string], undefined>,
  'deleteComplianceControl' : ActorMethod<[string], undefined>,
  'deleteCrosswalkMapping' : ActorMethod<
    [Standard, string, Standard, string],
    undefined
  >,
  'deleteEvidenceRecord' : ActorMethod<[string], undefined>,
  'deleteImplementationTask' : ActorMethod<[string], undefined>,
  'getAllAssessments' : ActorMethod<[], Array<Assessment>>,
  'getAllComplianceControls' : ActorMethod<[], Array<ComplianceControl>>,
  'getAllCrosswalkMappings' : ActorMethod<[], Array<CrosswalkMapping>>,
  'getAllEvidenceRecords' : ActorMethod<[], Array<EvidenceRecord>>,
  'getAllImplementationTasks' : ActorMethod<[], Array<ImplementationTask>>,
  'getAssessment' : ActorMethod<[string], Assessment>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComplianceControl' : ActorMethod<[string], ComplianceControl>,
  'getComplianceReport' : ActorMethod<[Standard], ComplianceReport>,
  'getControlsByStandard' : ActorMethod<[Standard], Array<ComplianceControl>>,
  'getCrosswalkMappings' : ActorMethod<
    [Standard, Standard],
    Array<CrosswalkMapping>
  >,
  'getEvidenceByControl' : ActorMethod<[string], Array<EvidenceRecord>>,
  'getEvidenceByStandard' : ActorMethod<[Standard], Array<EvidenceRecord>>,
  'getEvidenceCoverageSummary' : ActorMethod<[], Array<[Standard, bigint]>>,
  'getEvidenceRecord' : ActorMethod<[string], EvidenceRecord>,
  'getImplementationTask' : ActorMethod<[string], ImplementationTask>,
  'getRecentAssessmentActivity' : ActorMethod<[bigint], Array<Assessment>>,
  'getTasksByPriority' : ActorMethod<[TaskPriority], Array<ImplementationTask>>,
  'getTasksByPrioritySorted' : ActorMethod<[], Array<ImplementationTask>>,
  'getTasksByStandard' : ActorMethod<[Standard], Array<ImplementationTask>>,
  'getUserAssessments' : ActorMethod<[Principal], Array<Assessment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAssessmentControlStatus' : ActorMethod<
    [string, string, ControlStatus],
    undefined
  >,
  'updateComplianceControl' : ActorMethod<[ComplianceControl], undefined>,
  'updateEvidenceRecord' : ActorMethod<
    [string, string, EvidenceType, EvidenceStatus, [] | [Time], string],
    undefined
  >,
  'updateImplementationTask' : ActorMethod<
    [string, string, string, TaskPriority, TaskStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];