/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface ImplementationTask {
    id: string;
    status: TaskStatus;
    title: string;
    createdAt: Time;
    createdBy: Principal;
    description: string;
    controlId: string;
    priority: TaskPriority;
    standard: Standard;
    linkedAssessmentId?: string;
}
export interface CrosswalkMapping {
    sourceControlId: string;
    sourceStandard: Standard;
    targetControlId: string;
    targetStandard: Standard;
}
export interface Assessment {
    id: string;
    createdAt: Time;
    user: Principal;
    controlsStatus: Array<[string, ControlStatus]>;
    lastUpdated: Time;
    standard: Standard;
}
export interface ComplianceControl {
    id: string;
    description: string;
    standard: Standard;
    family: ControlFamily;
}
export interface EvidenceRecord {
    id: string;
    status: EvidenceStatus;
    expiryDate?: Time;
    name: string;
    createdAt: Time;
    createdBy: Principal;
    controlId: string;
    notes: string;
    standard: Standard;
    linkedAssessmentId?: string;
    evidenceType: EvidenceType;
}
export interface ComplianceReport {
    notApplicableCount: bigint;
    partialCount: bigint;
    compliantCount: bigint;
    totalControls: bigint;
    nonCompliantCount: bigint;
    standard: Standard;
    compliancePercentage: number;
}
export interface UserProfile {
    name: string;
    role: string;
    organization: string;
}
export enum ControlFamily {
    Physical_Security = "Physical_Security",
    Security_Assessment = "Security_Assessment",
    Continuous_Monitoring = "Continuous_Monitoring",
    Cryptography = "Cryptography",
    Asset_Management = "Asset_Management",
    Communications_Security = "Communications_Security",
    Access_Control = "Access_Control",
    Operations_Security = "Operations_Security"
}
export enum ControlStatus {
    NotApplicable = "NotApplicable",
    NonCompliant = "NonCompliant",
    Partial_ = "Partial",
    Compliant = "Compliant"
}
export enum EvidenceStatus {
    Active = "Active",
    Expired = "Expired",
    Pending = "Pending"
}
export enum EvidenceType {
    Log = "Log",
    Policy = "Policy",
    Document = "Document",
    Screenshot = "Screenshot"
}
export enum Standard {
    NIST_CSF = "NIST_CSF",
    CMMC = "CMMC",
    SOC2 = "SOC2",
    NERC_CIP = "NERC_CIP",
    ISO27001 = "ISO27001",
    IEC62443 = "IEC62443"
}
export enum TaskPriority {
    Low = "Low",
    High = "High",
    Medium = "Medium"
}
export enum TaskStatus {
    OnHold = "OnHold",
    Open = "Open",
    InProgress = "InProgress",
    Completed = "Completed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addComplianceControl(control: ComplianceControl): Promise<void>;
    addCrosswalkMapping(mapping: CrosswalkMapping): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAssessment(standard: Standard): Promise<string>;
    createEvidenceRecord(controlId: string, standard: Standard, name: string, evidenceType: EvidenceType, status: EvidenceStatus, expiryDate: Time | null, notes: string, linkedAssessmentId: string | null): Promise<string>;
    createImplementationTask(controlId: string, standard: Standard, title: string, description: string, priority: TaskPriority, linkedAssessmentId: string | null): Promise<string>;
    deleteAssessment(assessmentId: string): Promise<void>;
    deleteComplianceControl(controlId: string): Promise<void>;
    deleteCrosswalkMapping(sourceStandard: Standard, sourceControlId: string, targetStandard: Standard, targetControlId: string): Promise<void>;
    deleteEvidenceRecord(evidenceId: string): Promise<void>;
    deleteImplementationTask(taskId: string): Promise<void>;
    getAllAssessments(): Promise<Array<Assessment>>;
    getAllComplianceControls(): Promise<Array<ComplianceControl>>;
    getAllCrosswalkMappings(): Promise<Array<CrosswalkMapping>>;
    getAllEvidenceRecords(): Promise<Array<EvidenceRecord>>;
    getAllImplementationTasks(): Promise<Array<ImplementationTask>>;
    getAssessment(assessmentId: string): Promise<Assessment>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getComplianceControl(controlId: string): Promise<ComplianceControl>;
    getComplianceReport(standard: Standard): Promise<ComplianceReport>;
    getControlsByStandard(standard: Standard): Promise<Array<ComplianceControl>>;
    getCrosswalkMappings(sourceStandard: Standard, targetStandard: Standard): Promise<Array<CrosswalkMapping>>;
    getEvidenceByControl(controlId: string): Promise<Array<EvidenceRecord>>;
    getEvidenceByStandard(standard: Standard): Promise<Array<EvidenceRecord>>;
    getEvidenceCoverageSummary(): Promise<Array<[Standard, bigint]>>;
    getEvidenceRecord(evidenceId: string): Promise<EvidenceRecord>;
    getImplementationTask(taskId: string): Promise<ImplementationTask>;
    getRecentAssessmentActivity(limit: bigint): Promise<Array<Assessment>>;
    getTasksByPriority(priority: TaskPriority): Promise<Array<ImplementationTask>>;
    getTasksByPrioritySorted(): Promise<Array<ImplementationTask>>;
    getTasksByStandard(standard: Standard): Promise<Array<ImplementationTask>>;
    getUserAssessments(user: Principal): Promise<Array<Assessment>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateAssessmentControlStatus(assessmentId: string, controlId: string, status: ControlStatus): Promise<void>;
    updateComplianceControl(control: ComplianceControl): Promise<void>;
    updateEvidenceRecord(evidenceId: string, name: string, evidenceType: EvidenceType, status: EvidenceStatus, expiryDate: Time | null, notes: string): Promise<void>;
    updateImplementationTask(taskId: string, title: string, description: string, priority: TaskPriority, status: TaskStatus): Promise<void>;
}
import type { Assessment as _Assessment, ComplianceControl as _ComplianceControl, ComplianceReport as _ComplianceReport, ControlFamily as _ControlFamily, ControlStatus as _ControlStatus, CrosswalkMapping as _CrosswalkMapping, EvidenceRecord as _EvidenceRecord, EvidenceStatus as _EvidenceStatus, EvidenceType as _EvidenceType, ImplementationTask as _ImplementationTask, Standard as _Standard, TaskPriority as _TaskPriority, TaskStatus as _TaskStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComplianceControl(arg0: ComplianceControl): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addComplianceControl(to_candid_ComplianceControl_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComplianceControl(to_candid_ComplianceControl_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addCrosswalkMapping(arg0: CrosswalkMapping): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCrosswalkMapping(to_candid_CrosswalkMapping_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCrosswalkMapping(to_candid_CrosswalkMapping_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAssessment(arg0: Standard): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssessment(to_candid_Standard_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssessment(to_candid_Standard_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createEvidenceRecord(arg0: string, arg1: Standard, arg2: string, arg3: EvidenceType, arg4: EvidenceStatus, arg5: Time | null, arg6: string, arg7: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvidenceRecord(arg0, to_candid_Standard_n3(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_EvidenceType_n11(this._uploadFile, this._downloadFile, arg3), to_candid_EvidenceStatus_n13(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvidenceRecord(arg0, to_candid_Standard_n3(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_EvidenceType_n11(this._uploadFile, this._downloadFile, arg3), to_candid_EvidenceStatus_n13(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async createImplementationTask(arg0: string, arg1: Standard, arg2: string, arg3: string, arg4: TaskPriority, arg5: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createImplementationTask(arg0, to_candid_Standard_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_TaskPriority_n17(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createImplementationTask(arg0, to_candid_Standard_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_TaskPriority_n17(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async deleteAssessment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAssessment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAssessment(arg0);
            return result;
        }
    }
    async deleteComplianceControl(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComplianceControl(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComplianceControl(arg0);
            return result;
        }
    }
    async deleteCrosswalkMapping(arg0: Standard, arg1: string, arg2: Standard, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCrosswalkMapping(to_candid_Standard_n3(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_Standard_n3(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCrosswalkMapping(to_candid_Standard_n3(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_Standard_n3(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async deleteEvidenceRecord(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvidenceRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvidenceRecord(arg0);
            return result;
        }
    }
    async deleteImplementationTask(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteImplementationTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteImplementationTask(arg0);
            return result;
        }
    }
    async getAllAssessments(): Promise<Array<Assessment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssessments();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssessments();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllComplianceControls(): Promise<Array<ComplianceControl>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllComplianceControls();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllComplianceControls();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCrosswalkMappings(): Promise<Array<CrosswalkMapping>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCrosswalkMappings();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCrosswalkMappings();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEvidenceRecords(): Promise<Array<EvidenceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvidenceRecords();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvidenceRecords();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllImplementationTasks(): Promise<Array<ImplementationTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllImplementationTasks();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllImplementationTasks();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssessment(arg0: string): Promise<Assessment> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssessment(arg0);
                return from_candid_Assessment_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssessment(arg0);
            return from_candid_Assessment_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComplianceControl(arg0: string): Promise<ComplianceControl> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplianceControl(arg0);
                return from_candid_ComplianceControl_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplianceControl(arg0);
            return from_candid_ComplianceControl_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComplianceReport(arg0: Standard): Promise<ComplianceReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplianceReport(to_candid_Standard_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ComplianceReport_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplianceReport(to_candid_Standard_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ComplianceReport_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getControlsByStandard(arg0: Standard): Promise<Array<ComplianceControl>> {
        if (this.processError) {
            try {
                const result = await this.actor.getControlsByStandard(to_candid_Standard_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getControlsByStandard(to_candid_Standard_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCrosswalkMappings(arg0: Standard, arg1: Standard): Promise<Array<CrosswalkMapping>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCrosswalkMappings(to_candid_Standard_n3(this._uploadFile, this._downloadFile, arg0), to_candid_Standard_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCrosswalkMappings(to_candid_Standard_n3(this._uploadFile, this._downloadFile, arg0), to_candid_Standard_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvidenceByControl(arg0: string): Promise<Array<EvidenceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvidenceByControl(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvidenceByControl(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvidenceByStandard(arg0: Standard): Promise<Array<EvidenceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvidenceByStandard(to_candid_Standard_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvidenceByStandard(to_candid_Standard_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvidenceCoverageSummary(): Promise<Array<[Standard, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvidenceCoverageSummary();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvidenceCoverageSummary();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvidenceRecord(arg0: string): Promise<EvidenceRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvidenceRecord(arg0);
                return from_candid_EvidenceRecord_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvidenceRecord(arg0);
            return from_candid_EvidenceRecord_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getImplementationTask(arg0: string): Promise<ImplementationTask> {
        if (this.processError) {
            try {
                const result = await this.actor.getImplementationTask(arg0);
                return from_candid_ImplementationTask_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImplementationTask(arg0);
            return from_candid_ImplementationTask_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentAssessmentActivity(arg0: bigint): Promise<Array<Assessment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentAssessmentActivity(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentAssessmentActivity(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByPriority(arg0: TaskPriority): Promise<Array<ImplementationTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByPriority(to_candid_TaskPriority_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByPriority(to_candid_TaskPriority_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByPrioritySorted(): Promise<Array<ImplementationTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByPrioritySorted();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByPrioritySorted();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByStandard(arg0: Standard): Promise<Array<ImplementationTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByStandard(to_candid_Standard_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByStandard(to_candid_Standard_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserAssessments(arg0: Principal): Promise<Array<Assessment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAssessments(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAssessments(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateAssessmentControlStatus(arg0: string, arg1: string, arg2: ControlStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAssessmentControlStatus(arg0, arg1, to_candid_ControlStatus_n59(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAssessmentControlStatus(arg0, arg1, to_candid_ControlStatus_n59(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateComplianceControl(arg0: ComplianceControl): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateComplianceControl(to_candid_ComplianceControl_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateComplianceControl(to_candid_ComplianceControl_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateEvidenceRecord(arg0: string, arg1: string, arg2: EvidenceType, arg3: EvidenceStatus, arg4: Time | null, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvidenceRecord(arg0, arg1, to_candid_EvidenceType_n11(this._uploadFile, this._downloadFile, arg2), to_candid_EvidenceStatus_n13(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvidenceRecord(arg0, arg1, to_candid_EvidenceType_n11(this._uploadFile, this._downloadFile, arg2), to_candid_EvidenceStatus_n13(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async updateImplementationTask(arg0: string, arg1: string, arg2: string, arg3: TaskPriority, arg4: TaskStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateImplementationTask(arg0, arg1, arg2, to_candid_TaskPriority_n17(this._uploadFile, this._downloadFile, arg3), to_candid_TaskStatus_n61(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateImplementationTask(arg0, arg1, arg2, to_candid_TaskPriority_n17(this._uploadFile, this._downloadFile, arg3), to_candid_TaskStatus_n61(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
}
function from_candid_Assessment_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Assessment): Assessment {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ComplianceControl_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ComplianceControl): ComplianceControl {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_ComplianceReport_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ComplianceReport): ComplianceReport {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_ControlFamily_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ControlFamily): ControlFamily {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_ControlStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ControlStatus): ControlStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_CrosswalkMapping_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CrosswalkMapping): CrosswalkMapping {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_EvidenceRecord_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EvidenceRecord): EvidenceRecord {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_EvidenceStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EvidenceStatus): EvidenceStatus {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_EvidenceType_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EvidenceType): EvidenceType {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_ImplementationTask_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImplementationTask): ImplementationTask {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Standard_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Standard): Standard {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_TaskPriority_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskPriority): TaskPriority {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    createdAt: _Time;
    user: Principal;
    controlsStatus: Array<[string, _ControlStatus]>;
    lastUpdated: _Time;
    standard: _Standard;
}): {
    id: string;
    createdAt: Time;
    user: Principal;
    controlsStatus: Array<[string, ControlStatus]>;
    lastUpdated: Time;
    standard: Standard;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        user: value.user,
        controlsStatus: from_candid_vec_n22(_uploadFile, _downloadFile, value.controlsStatus),
        lastUpdated: value.lastUpdated,
        standard: from_candid_Standard_n26(_uploadFile, _downloadFile, value.standard)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    description: string;
    standard: _Standard;
    family: _ControlFamily;
}): {
    id: string;
    description: string;
    standard: Standard;
    family: ControlFamily;
} {
    return {
        id: value.id,
        description: value.description,
        standard: from_candid_Standard_n26(_uploadFile, _downloadFile, value.standard),
        family: from_candid_ControlFamily_n31(_uploadFile, _downloadFile, value.family)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sourceControlId: string;
    sourceStandard: _Standard;
    targetControlId: string;
    targetStandard: _Standard;
}): {
    sourceControlId: string;
    sourceStandard: Standard;
    targetControlId: string;
    targetStandard: Standard;
} {
    return {
        sourceControlId: value.sourceControlId,
        sourceStandard: from_candid_Standard_n26(_uploadFile, _downloadFile, value.sourceStandard),
        targetControlId: value.targetControlId,
        targetStandard: from_candid_Standard_n26(_uploadFile, _downloadFile, value.targetStandard)
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _EvidenceStatus;
    expiryDate: [] | [_Time];
    name: string;
    createdAt: _Time;
    createdBy: Principal;
    controlId: string;
    notes: string;
    standard: _Standard;
    linkedAssessmentId: [] | [string];
    evidenceType: _EvidenceType;
}): {
    id: string;
    status: EvidenceStatus;
    expiryDate?: Time;
    name: string;
    createdAt: Time;
    createdBy: Principal;
    controlId: string;
    notes: string;
    standard: Standard;
    linkedAssessmentId?: string;
    evidenceType: EvidenceType;
} {
    return {
        id: value.id,
        status: from_candid_EvidenceStatus_n39(_uploadFile, _downloadFile, value.status),
        expiryDate: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.expiryDate)),
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        controlId: value.controlId,
        notes: value.notes,
        standard: from_candid_Standard_n26(_uploadFile, _downloadFile, value.standard),
        linkedAssessmentId: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.linkedAssessmentId)),
        evidenceType: from_candid_EvidenceType_n43(_uploadFile, _downloadFile, value.evidenceType)
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _TaskStatus;
    title: string;
    createdAt: _Time;
    createdBy: Principal;
    description: string;
    controlId: string;
    priority: _TaskPriority;
    standard: _Standard;
    linkedAssessmentId: [] | [string];
}): {
    id: string;
    status: TaskStatus;
    title: string;
    createdAt: Time;
    createdBy: Principal;
    description: string;
    controlId: string;
    priority: TaskPriority;
    standard: Standard;
    linkedAssessmentId?: string;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n48(_uploadFile, _downloadFile, value.status),
        title: value.title,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        description: value.description,
        controlId: value.controlId,
        priority: from_candid_TaskPriority_n50(_uploadFile, _downloadFile, value.priority),
        standard: from_candid_Standard_n26(_uploadFile, _downloadFile, value.standard),
        linkedAssessmentId: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.linkedAssessmentId))
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notApplicableCount: bigint;
    partialCount: bigint;
    compliantCount: bigint;
    totalControls: bigint;
    nonCompliantCount: bigint;
    standard: _Standard;
    compliancePercentage: number;
}): {
    notApplicableCount: bigint;
    partialCount: bigint;
    compliantCount: bigint;
    totalControls: bigint;
    nonCompliantCount: bigint;
    standard: Standard;
    compliancePercentage: number;
} {
    return {
        notApplicableCount: value.notApplicableCount,
        partialCount: value.partialCount,
        compliantCount: value.compliantCount,
        totalControls: value.totalControls,
        nonCompliantCount: value.nonCompliantCount,
        standard: from_candid_Standard_n26(_uploadFile, _downloadFile, value.standard),
        compliancePercentage: value.compliancePercentage
    };
}
function from_candid_tuple_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _ControlStatus]): [string, ControlStatus] {
    return [
        value[0],
        from_candid_ControlStatus_n24(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Standard, bigint]): [Standard, bigint] {
    return [
        from_candid_Standard_n26(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    NotApplicable: null;
} | {
    NonCompliant: null;
} | {
    Partial: null;
} | {
    Compliant: null;
}): ControlStatus {
    return "NotApplicable" in value ? ControlStatus.NotApplicable : "NonCompliant" in value ? ControlStatus.NonCompliant : "Partial" in value ? ControlStatus.Partial : "Compliant" in value ? ControlStatus.Compliant : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    NIST_CSF: null;
} | {
    CMMC: null;
} | {
    SOC2: null;
} | {
    NERC_CIP: null;
} | {
    ISO27001: null;
} | {
    IEC62443: null;
}): Standard {
    return "NIST_CSF" in value ? Standard.NIST_CSF : "CMMC" in value ? Standard.CMMC : "SOC2" in value ? Standard.SOC2 : "NERC_CIP" in value ? Standard.NERC_CIP : "ISO27001" in value ? Standard.ISO27001 : "IEC62443" in value ? Standard.IEC62443 : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Physical_Security: null;
} | {
    Security_Assessment: null;
} | {
    Continuous_Monitoring: null;
} | {
    Cryptography: null;
} | {
    Asset_Management: null;
} | {
    Communications_Security: null;
} | {
    Access_Control: null;
} | {
    Operations_Security: null;
}): ControlFamily {
    return "Physical_Security" in value ? ControlFamily.Physical_Security : "Security_Assessment" in value ? ControlFamily.Security_Assessment : "Continuous_Monitoring" in value ? ControlFamily.Continuous_Monitoring : "Cryptography" in value ? ControlFamily.Cryptography : "Asset_Management" in value ? ControlFamily.Asset_Management : "Communications_Security" in value ? ControlFamily.Communications_Security : "Access_Control" in value ? ControlFamily.Access_Control : "Operations_Security" in value ? ControlFamily.Operations_Security : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Active: null;
} | {
    Expired: null;
} | {
    Pending: null;
}): EvidenceStatus {
    return "Active" in value ? EvidenceStatus.Active : "Expired" in value ? EvidenceStatus.Expired : "Pending" in value ? EvidenceStatus.Pending : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Log: null;
} | {
    Policy: null;
} | {
    Document: null;
} | {
    Screenshot: null;
}): EvidenceType {
    return "Log" in value ? EvidenceType.Log : "Policy" in value ? EvidenceType.Policy : "Document" in value ? EvidenceType.Document : "Screenshot" in value ? EvidenceType.Screenshot : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    OnHold: null;
} | {
    Open: null;
} | {
    InProgress: null;
} | {
    Completed: null;
}): TaskStatus {
    return "OnHold" in value ? TaskStatus.OnHold : "Open" in value ? TaskStatus.Open : "InProgress" in value ? TaskStatus.InProgress : "Completed" in value ? TaskStatus.Completed : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
}): TaskPriority {
    return "Low" in value ? TaskPriority.Low : "High" in value ? TaskPriority.High : "Medium" in value ? TaskPriority.Medium : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Assessment>): Array<Assessment> {
    return value.map((x)=>from_candid_Assessment_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _ControlStatus]>): Array<[string, ControlStatus]> {
    return value.map((x)=>from_candid_tuple_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ComplianceControl>): Array<ComplianceControl> {
    return value.map((x)=>from_candid_ComplianceControl_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CrosswalkMapping>): Array<CrosswalkMapping> {
    return value.map((x)=>from_candid_CrosswalkMapping_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EvidenceRecord>): Array<EvidenceRecord> {
    return value.map((x)=>from_candid_EvidenceRecord_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ImplementationTask>): Array<ImplementationTask> {
    return value.map((x)=>from_candid_ImplementationTask_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Standard, bigint]>): Array<[Standard, bigint]> {
    return value.map((x)=>from_candid_tuple_n58(_uploadFile, _downloadFile, x));
}
function to_candid_ComplianceControl_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ComplianceControl): _ComplianceControl {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ControlFamily_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ControlFamily): _ControlFamily {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ControlStatus_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ControlStatus): _ControlStatus {
    return to_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function to_candid_CrosswalkMapping_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CrosswalkMapping): _CrosswalkMapping {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_EvidenceStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EvidenceStatus): _EvidenceStatus {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_EvidenceType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EvidenceType): _EvidenceType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Standard_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Standard): _Standard {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TaskPriority_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): _TaskPriority {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    description: string;
    standard: Standard;
    family: ControlFamily;
}): {
    id: string;
    description: string;
    standard: _Standard;
    family: _ControlFamily;
} {
    return {
        id: value.id,
        description: value.description,
        standard: to_candid_Standard_n3(_uploadFile, _downloadFile, value.standard),
        family: to_candid_ControlFamily_n5(_uploadFile, _downloadFile, value.family)
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sourceControlId: string;
    sourceStandard: Standard;
    targetControlId: string;
    targetStandard: Standard;
}): {
    sourceControlId: string;
    sourceStandard: _Standard;
    targetControlId: string;
    targetStandard: _Standard;
} {
    return {
        sourceControlId: value.sourceControlId,
        sourceStandard: to_candid_Standard_n3(_uploadFile, _downloadFile, value.sourceStandard),
        targetControlId: value.targetControlId,
        targetStandard: to_candid_Standard_n3(_uploadFile, _downloadFile, value.targetStandard)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EvidenceType): {
    Log: null;
} | {
    Policy: null;
} | {
    Document: null;
} | {
    Screenshot: null;
} {
    return value == EvidenceType.Log ? {
        Log: null
    } : value == EvidenceType.Policy ? {
        Policy: null
    } : value == EvidenceType.Document ? {
        Document: null
    } : value == EvidenceType.Screenshot ? {
        Screenshot: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EvidenceStatus): {
    Active: null;
} | {
    Expired: null;
} | {
    Pending: null;
} {
    return value == EvidenceStatus.Active ? {
        Active: null
    } : value == EvidenceStatus.Expired ? {
        Expired: null
    } : value == EvidenceStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} {
    return value == TaskPriority.Low ? {
        Low: null
    } : value == TaskPriority.High ? {
        High: null
    } : value == TaskPriority.Medium ? {
        Medium: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Standard): {
    NIST_CSF: null;
} | {
    CMMC: null;
} | {
    SOC2: null;
} | {
    NERC_CIP: null;
} | {
    ISO27001: null;
} | {
    IEC62443: null;
} {
    return value == Standard.NIST_CSF ? {
        NIST_CSF: null
    } : value == Standard.CMMC ? {
        CMMC: null
    } : value == Standard.SOC2 ? {
        SOC2: null
    } : value == Standard.NERC_CIP ? {
        NERC_CIP: null
    } : value == Standard.ISO27001 ? {
        ISO27001: null
    } : value == Standard.IEC62443 ? {
        IEC62443: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ControlFamily): {
    Physical_Security: null;
} | {
    Security_Assessment: null;
} | {
    Continuous_Monitoring: null;
} | {
    Cryptography: null;
} | {
    Asset_Management: null;
} | {
    Communications_Security: null;
} | {
    Access_Control: null;
} | {
    Operations_Security: null;
} {
    return value == ControlFamily.Physical_Security ? {
        Physical_Security: null
    } : value == ControlFamily.Security_Assessment ? {
        Security_Assessment: null
    } : value == ControlFamily.Continuous_Monitoring ? {
        Continuous_Monitoring: null
    } : value == ControlFamily.Cryptography ? {
        Cryptography: null
    } : value == ControlFamily.Asset_Management ? {
        Asset_Management: null
    } : value == ControlFamily.Communications_Security ? {
        Communications_Security: null
    } : value == ControlFamily.Access_Control ? {
        Access_Control: null
    } : value == ControlFamily.Operations_Security ? {
        Operations_Security: null
    } : value;
}
function to_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ControlStatus): {
    NotApplicable: null;
} | {
    NonCompliant: null;
} | {
    Partial: null;
} | {
    Compliant: null;
} {
    return value == ControlStatus.NotApplicable ? {
        NotApplicable: null
    } : value == ControlStatus.NonCompliant ? {
        NonCompliant: null
    } : value == ControlStatus.Partial ? {
        Partial_: null
    } : value == ControlStatus.Compliant ? {
        Compliant: null
    } : value;
}
function to_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    OnHold: null;
} | {
    Open: null;
} | {
    InProgress: null;
} | {
    Completed: null;
} {
    return value == TaskStatus.OnHold ? {
        OnHold: null
    } : value == TaskStatus.Open ? {
        Open: null
    } : value == TaskStatus.InProgress ? {
        InProgress: null
    } : value == TaskStatus.Completed ? {
        Completed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
